### ISSUE TITLE
how to interpret the x/y axis in figure 6?

### ISSUE THREAD

**Issue by Tsingularity** [davidbau/ganseeing#3]
Thanks for the great work!
But I am a little bit confused about the plots in figure 6. There are 3 rows of co-relation plots in it (shown as below). However, I don't see any explanation in the paper about how to interpret the x/y axis. Take the middle row for example, both the true and reconstructed layer4 feature are high-dimensional vectors. So what does the x/y axis means? Norm or something else? 
Thanks in advance!
![image](https://user-images.githubusercontent.com/13026942/97238589-16e1f980-17c0-11eb-88ab-77a3fb9d3c34.png)

**Comment by davidbau** [comment]
In these scatterplots I ignore distinctions between different channels and
pixels and plot raw feature components on the x axis against the
corresponding reconstructed feature component on the y axis.

For example, if you had three images represented as 2x2 feature-maps with
five channels each, that is 3x2x2x5 = 60 scalar features in total.  Then if
you reconstruct those three representations you will get another 60 scalar
features.  To see how much these reconstructions agree with the originals,
you can plot sixty points with (orig_i, recons_i) for each i over all
3x2x2x5 features.  In the real scatterplots, of course I evaluate much
larger featuremaps over larger sets of images. RGB images have 3 feeatures
pixel pixel.  Latent values have a large vector of features and only one
pixel... Same method.

Perfect reconstructions will lie on the line x==y.

**Comment by Tsingularity** [comment]
Thanks for the explanations! They are very useful.
